// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg-yvlWe3gB83YhFj3HF7-VFYmUNXPpFg',
    appId: '1:428983193335:android:a72e6188a1bbe376b80df2',
    messagingSenderId: '428983193335',
    projectId: 'promoruta-b0905',
    storageBucket: 'promoruta-b0905.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtY_zxu0GLu9xRydRaAuWkokfSRw1XDk8',
    appId: '1:428983193335:ios:12ad3437fc9fa4a8b80df2',
    messagingSenderId: '428983193335',
    projectId: 'promoruta-b0905',
    storageBucket: 'promoruta-b0905.firebasestorage.app',
    iosBundleId: 'com.promoruta.app.promoruta',
  );
}
