// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD4ibQ8_jK-b6n9CKEBZ2AB0oNTpTGGiQ',
    appId: '1:428983193335:web:a4d1180caa016279b80df2',
    messagingSenderId: '428983193335',
    projectId: 'promoruta-b0905',
    authDomain: 'promoruta-b0905.firebaseapp.com',
    storageBucket: 'promoruta-b0905.firebasestorage.app',
    measurementId: 'G-2RH9P8NRXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg-yvlWe3gB83YhFj3HF7-VFYmUNXPpFg',
    appId: '1:428983193335:android:a72e6188a1bbe376b80df2',
    messagingSenderId: '428983193335',
    projectId: 'promoruta-b0905',
    storageBucket: 'promoruta-b0905.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtY_zxu0GLu9xRydRaAuWkokfSRw1XDk8',
    appId: '1:428983193335:ios:12ad3437fc9fa4a8b80df2',
    messagingSenderId: '428983193335',
    projectId: 'promoruta-b0905',
    storageBucket: 'promoruta-b0905.firebasestorage.app',
    iosBundleId: 'com.promoruta.app.promoruta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtY_zxu0GLu9xRydRaAuWkokfSRw1XDk8',
    appId: '1:428983193335:ios:12ad3437fc9fa4a8b80df2',
    messagingSenderId: '428983193335',
    projectId: 'promoruta-b0905',
    storageBucket: 'promoruta-b0905.firebasestorage.app',
    iosBundleId: 'com.promoruta.app.promoruta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD4ibQ8_jK-b6n9CKEBZ2AB0oNTpTGGiQ',
    appId: '1:428983193335:web:d0b4e8fa01bd4cb5b80df2',
    messagingSenderId: '428983193335',
    projectId: 'promoruta-b0905',
    authDomain: 'promoruta-b0905.firebaseapp.com',
    storageBucket: 'promoruta-b0905.firebasestorage.app',
    measurementId: 'G-WBH78SMBJJ',
  );
}
